### ISSUE TITLE
Address

### ISSUE THREAD

**Issue by CyberAnfric** [cullinan-finance/sugarswap-frontend#1]
weth  0x3Dce90068b23288F07cA95901058e12878112069
sushiToken 0xa76fd9def6C3BD0Fc991d32eD33Ec978F5bd8c75
factory 0xA675b6EE10bCc39913e599AE9eF396BdD80056f0
router 0xED5e063ccB45c4Bfc6EBac4AAAc91E95A6C07a10
masterChef 0x40d25dC110109BD0862E486f99Ce451A6E25Ac83
testTokenA 0x6A8aA46b62ec8e613fd22cfF8c381FC47f469e3a
testPair(SLP) 0x43016D7A6f33e551361E7C1Ef0CeE1deD02dab46

**Comment by SugarLeek** [comment]
coool
